name: backend-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fastapi
  - uvicorn
  - pip
  - pip:
      - hummingbot
      - numpy==1.26.4
#      - docker
      - git+https://github.com/felixfontein/docker-py
      - python-dotenv
      - boto3
      - python-multipart
      - PyYAML
      - apscheduler
      - git+https://github.com/hummingbot/hbot-remote-client-py.git
