name: backend-api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fastapi
  - uvicorn
  - libcxx
  - pip
  - pip:
      - hummingbot==20241125
      - numpy==1.26.4
      - git+https://github.com/felixfontein/docker-py
      - python-dotenv
      - boto3
      - python-multipart==0.0.12
      - PyYAML
      - git+https://github.com/hummingbot/hbot-remote-client-py.git
      - flake8
      - isort
      - pre-commit
